name: Déploiement Todo-App

on:
  workflow_run:
    workflows: ["CI"]   # Nom exact de ton workflow CI
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Exécuter le playbook Ansible
        run: ansible-playbook -i inventory.ini playbook.yml
