name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Créer et activer venv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le projet
        run: |
          source venv/bin/activate
          python src/main.py

      - name: Lancer tests avec pytest
        run: |
          source venv/bin/activate
          pytest
          
      - name: Notifier Discord succès
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"CI réussie pour rep \`${{ github.repository }}\` sur \`${{ github.ref_name }}\` par ${{ github.actor }}. [Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notifier Discord échec
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"⚠️ CI échouée pour \`${{ github.repository }}\` sur \`${{ github.ref_name }}\` par ${{ github.actor }}. [Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
